CREATE TABLE IF NOT EXISTS public.motion_telemetry_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid NOT NULL REFERENCES public.motion_sessions(id) ON DELETE CASCADE,
  sample_index integer NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  altitude_meters double precision,
  speed_2d_mps double precision,
  speed_3d_mps double precision,
  source text NOT NULL DEFAULT 'gopro_gpmf',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, sample_index)
);

CREATE INDEX IF NOT EXISTS motion_telemetry_samples_session_id_idx
  ON public.motion_telemetry_samples(session_id);

ALTER TABLE public.motion_telemetry_samples ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS motion_telemetry_samples_select_own
  ON public.motion_telemetry_samples;
CREATE POLICY motion_telemetry_samples_select_own
  ON public.motion_telemetry_samples FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS motion_telemetry_samples_insert_own
  ON public.motion_telemetry_samples;
CREATE POLICY motion_telemetry_samples_insert_own
  ON public.motion_telemetry_samples FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS motion_telemetry_samples_delete_own
  ON public.motion_telemetry_samples;
CREATE POLICY motion_telemetry_samples_delete_own
  ON public.motion_telemetry_samples FOR DELETE TO authenticated
  USING (auth.uid() = user_id);
